### ISSUE TITLE
Why the CUDA is getting out of memory

### ISSUE THREAD

**Issue by SujithKumar01** [gabrielmittag/NISQA#51]
I had runned on GPU with 16GB. I gave an Audio length of 33 mins and also changed the ms_max_segments=60000

Device: cuda
Model architecture: NISQA_DIM
Loaded pretrained model from weights/nisqa_2.tar
---> Predicting ...
/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/librosa/feature/spectral.py:2143: UserWarning: Empty filters detected in mel frequency basis. Some channels will produce empty responses. Try increasing your sampling rate (and fmax) or reducing n_mels.
  mel_basis = filters.mel(sr=sr, n_fft=n_fft, **kwargs)
Traceback (most recent call last):
  File "run_predict.py", line 43, in <module>
    nisqa.predict()
  File "/home/demo/Documents/Audioassessment/NISQA/nisqa/NISQA_model.py", line 60, in predict
    y_val_hat, y_val = NL.predict_dim(
  File "/home/demo/Documents/Audioassessment/NISQA/nisqa/NISQA_lib.py", line 1455, in predict_dim
    y_hat_list = [ [model(xb.to(dev), n_wins.to(dev)).cpu().numpy(), yb.cpu().numpy()] for xb, yb, (idx, n_wins) in dl]
  File "/home/demo/Documents/Audioassessment/NISQA/nisqa/NISQA_lib.py", line 1455, in <listcomp>
    y_hat_list = [ [model(xb.to(dev), n_wins.to(dev)).cpu().numpy(), yb.cpu().numpy()] for xb, yb, (idx, n_wins) in dl]
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/demo/Documents/Audioassessment/NISQA/nisqa/NISQA_lib.py", line 263, in forward
    x, n_wins = self.time_dependency(x, n_wins)
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/demo/Documents/Audioassessment/NISQA/nisqa/NISQA_lib.py", line 894, in forward
    x, n_wins = self.model(x, n_wins)
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/demo/Documents/Audioassessment/NISQA/nisqa/NISQA_lib.py", line 995, in forward
    output, n_wins = mod(output, n_wins=n_wins)
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/demo/Documents/Audioassessment/NISQA/nisqa/NISQA_lib.py", line 1032, in forward
    src2 = self.self_attn(src, src, src, key_padding_mask=mask)[0]
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1266, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/functional.py", line 5470, in multi_head_attention_forward
    attn_output_weights = softmax(attn_output_weights, dim=-1)
  File "/home/demo/Documents/Audioassessment/nisqaenv/lib/python3.8/site-packages/torch/nn/functional.py", line 1885, in softmax
    ret = input.softmax(dim)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 9.21 GiB. GPU

**Comment by gabrielmittag** [comment]
33 minutes is quite long. I would suggest to split up the file into multiple smaller segments, for example with duration 30 secondsm, and run the model on each segment.
